name: 'GitHub Slack notifications'
description: 'Sends Slack notifications about the results of GitHub Actions'
inputs:
  aws-role-arn:
    description: 'AWS role to be assumed by the action'
    required: false
    default: 'arn:aws:iam::365562660444:role/github_iam_role'
  aws-region:
    description: 'AWS region'
    required: false
    default: 'ap-southeast-2'
  slack-channel:
    description: 'Slack channel to send notifications to'
    required: false
    default: 'github-actions'
runs:
  using: node24
  main: 'dist/index.js'